import {StyleSheet} from 'react-native';
import {
  responsiveScreenFontSize,
  responsiveScreenHeight,
  responsiveScreenWidth,
} from 'react-native-responsive-dimensions';

const HomeStyle = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // padding: 20,
  },
  input: {
    width: responsiveScreenWidth(70),
    padding: responsiveScreenHeight(2),
    // borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 20,
  },
  button: {
    backgroundColor: '#007AFF',
    width: responsiveScreenWidth(60),
    padding: responsiveScreenHeight(2),

    borderRadius: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  DrawerButton: {
    // backgroundColor:"red",
    width: responsiveScreenWidth(20),
    padding: responsiveScreenHeight(2),
    position: 'absolute',
    top: responsiveScreenHeight(1),
    left: responsiveScreenWidth(-2),
    borderRadius: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  NotificationButton: {
    // backgroundColor:"red",
    width: responsiveScreenWidth(20),
    padding: responsiveScreenHeight(2),
    position: 'absolute',
    top: responsiveScreenHeight(1),
    right: responsiveScreenWidth(-2),
    borderRadius: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  MapButton: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    backgroundColor: '#007AFF',
    width: responsiveScreenWidth(60),
    padding: responsiveScreenHeight(2),

    borderRadius: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  KMButton: {
    position: 'absolute',
    left: 10,
    right: 20,
    backgroundColor: '#007AFF',
    width: responsiveScreenWidth(60),
    padding: responsiveScreenHeight(2),

    borderRadius: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  KMButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    backgroundColor: '#007AFF',
    width: responsiveScreenWidth(60),
    padding: responsiveScreenHeight(2),

    borderRadius: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  OnlineButton: {
    position: 'absolute',
    left: 80,
    top: 35,
    backgroundColor: '#fff',
    width: responsiveScreenWidth(50),
    padding: responsiveScreenHeight(1),
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: responsiveScreenWidth(2),
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  OtpButton: {
    position: 'absolute',
    bottom: 0,
    right: 20,
    backgroundColor: '#007AFF',
    width: responsiveScreenWidth(60),
    padding: responsiveScreenHeight(2),

    borderRadius: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    // alignItems: 'center',
  },
  title: {
    fontSize: responsiveScreenFontSize(2),
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#000',
  },
  subTitle: {
    fontSize: responsiveScreenFontSize(2),
    fontWeight: '200',
    marginBottom: 15,
    color: 'grey',
  },
  codeFieldRoot: {
    marginBottom: 20,
  },
  cell: {
    width: 50,
    height: 50,
    lineHeight: 48,
    fontSize: 24,
    borderWidth: 2,
    borderColor: '#ccc',
    textAlign: 'center',
    borderRadius: 8,
    marginHorizontal: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  focusCell: {
    borderColor: '#007AFF',
  },
  cellText: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  MapModalText: {
    fontSize: 18,
    marginBottom: 20,
  },
  MapCloseButton: {
    backgroundColor: '#FF3B30',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  MapCloseButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  MapModalContent: {
    backgroundColor: '#fff',
    padding: 20,
    borderTopLeftRadius: responsiveScreenHeight(4),
    borderTopRightRadius: responsiveScreenHeight(4),
    alignItems: 'center',
    height: responsiveScreenHeight(80),
  },
  MapHandle: {
    width: 40,
    height: 5,
    backgroundColor: '#ccc',
    borderRadius: 5,
    marginBottom: 10,
  },
  step: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  textSteps: {
    fontSize: 14,
    color: '#333',
  },
  line: {
    marginLeft: 9, // Align with icons
  },
  dash: {
    width: responsiveScreenWidth(1), // Vertical Line
    height: 100, // Adjust height
    flexDirection: 'column', // For vertical alignment
  },
  map: {
    // flex: 1,
    height: '100%',
    width: '100%',
  },
  AcceptModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  AcceptModalContent: {
    width: '80%',
    height: '30%',
    borderRadius: 10,
    overflow: 'hidden',
  },
  AcceptBlueSection: {
    flex: 1,
    backgroundColor: '#0C3384',
    justifyContent: 'center',
    alignItems: 'center',
  },
  AcceptWhiteSection: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  AcceptModalText: {
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    color: '#000',
    marginBottom: 20,
  },
  AcceptButtonContainer: {
    flexDirection: 'row',
    gap: 15,
  },
  AcceptNoButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#0C3384',
    flexDirection: 'row',
    alignItems: 'center',
  },
  AcceptYesButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    backgroundColor: '#0C3384',
    flexDirection: 'row',
    alignItems: 'center',
  },
  AcceptNoText: {
    color: '#0C3384',
    fontWeight: '600',
    paddingLeft: responsiveScreenWidth(1),
  },
  AcceptYesText: {
    color: '#fff',
    fontWeight: '600',
    paddingLeft: responsiveScreenWidth(1),
  },
  DrawerImg: {
    height: responsiveScreenHeight(6),
    width: responsiveScreenWidth(8),
  },
  HomeOnlineBtn: {
    width: responsiveScreenHeight(2),
    height: responsiveScreenHeight(2),
    borderRadius: responsiveScreenHeight(1),
    backgroundColor: 'green',
    alignItems: 'center',
  },
  RowOnlineView: {flexDirection: 'row'},
  BellNotificationImg: {
    height: responsiveScreenHeight(6),
    width: responsiveScreenWidth(8),
    tintColor: 'Blue',
  },
  BasicTickImgView: {
    height: responsiveScreenHeight(8),
    width: responsiveScreenHeight(8),
    borderRadius: responsiveScreenHeight(4),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#396ACFFC',
  },
  BasicTickImg: {
    height: responsiveScreenHeight(4),
    width: responsiveScreenWidth(8),
    tintColor: '#fff',
  },
  CancelYesBtnView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
});
export default HomeStyle;
