import {StyleSheet} from 'react-native';
import {
  responsiveScreenFontSize,
  responsiveScreenHeight,
  responsiveScreenWidth,
} from 'react-native-responsive-dimensions';
const WalletStyle = StyleSheet.create({
  container: {
    alignItems: 'center',
    marginTop: 50,
  },
  switchContainer: {
    width: 400,
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ccc',
    flexDirection: 'row',
    position: 'relative',
  },
  slider: {
    position: 'absolute',
    width: '50%',
    height: '100%',
    backgroundColor: '#0A2C7D',
    borderRadius: 25,
  },
  option: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0A2C7D',
  },
  selectedText: {
    color: '#fff',
  },
  AddTollRequestBtn: {
    color: '#3b22e0',
    fontSize: responsiveScreenFontSize(2),
    fontWeight: '500',
    lineHeight: 20,
  },
  MainContainer: {flex: 1},
  AvailableBalanceText: {
    fontWeight: '400',
    fontSize: responsiveScreenFontSize(2),
    lineHeight: 36,
    color: '#fff',
  },
  AvailableBalanceTextValue: {
    fontWeight: '400',
    fontSize: responsiveScreenFontSize(2),
    lineHeight: 36,
    color: '#fff',
  },
  AvailableBalanceView: {
    padding: responsiveScreenHeight(3),
    backgroundColor: '#0C3384',
    justifyContent: 'center',
    alignItems: 'center',
    width: responsiveScreenWidth(60),
    borderRadius: responsiveScreenWidth(4),
  },
  AvailableBalanceViewContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: responsiveScreenHeight(4),
  },
  RecentTransactionsText: {
    fontWeight: '700',
    fontSize: responsiveScreenFontSize(2),
    lineHeight: 40,
    color: 'grey',
  },
  RecentTransactionsTextView: {
    paddingLeft: responsiveScreenWidth(5),
    paddingRight: responsiveScreenWidth(5),
    paddingTop: responsiveScreenHeight(3),
  },
  AmountText: {
    fontWeight: '700',
    fontSize: responsiveScreenFontSize(2),
    lineHeight: 40,
    color: '#000',
  },
  DateTimeText: {
    fontWeight: '400',
    fontSize: responsiveScreenFontSize(2),
    lineHeight: 40,
    color: '#000',
  },
  CommissionText: {
    fontWeight: '700',
    fontSize: responsiveScreenFontSize(2),
    lineHeight: 20,
    color: '#000',
  },
  DebitText: {
    fontWeight: '700',
    fontSize: responsiveScreenFontSize(2),
    lineHeight: 20,
    color: '#000',
  },
  commissionView: {paddingTop: responsiveScreenHeight(4)},
  DashText: {
    fontWeight: 'bold',
    fontSize: responsiveScreenFontSize(3),
    lineHeight: 40,
    color: '#0C3384',
  },
  DashTextView: {
    width: responsiveScreenWidth(10),
    height: responsiveScreenHeight(4),
    backgroundColor: 'grey',
    borderRadius: responsiveScreenWidth(2),
    justifyContent: 'center',
    alignItems: 'center',
  },
  listRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  listContainer: {
    borderWidth: 1,
    borderColor: 'grey',
    width: responsiveScreenWidth(90),
    borderRadius: responsiveScreenWidth(2),
    padding: responsiveScreenHeight(1),
  },
  header: {
    height: 80,
    width: '100%',
    backgroundColor: '#0C3384',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: responsiveScreenWidth(4),
  },
  backIcon: {
    height: responsiveScreenHeight(6),
    width: responsiveScreenWidth(12),
  },
  headerTitle: {
    fontWeight: '700',
    fontSize: responsiveScreenFontSize(3),
    lineHeight: 40,
    color: '#FFF',
    marginLeft: responsiveScreenWidth(5),
  },
  AddTollRequestBtnView: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: responsiveScreenHeight(3),
    paddingBottom: responsiveScreenHeight(12),
  },
  AddTollRequestButton: {
    backgroundColor: '#ebd1ff',
    width: responsiveScreenWidth(90),
    padding: responsiveScreenWidth(1),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: responsiveScreenWidth(6),
  },
  ListReasonView: {paddingBottom: responsiveScreenHeight(2)},
});
export default WalletStyle;
