// Styling
import {StyleSheet} from 'react-native';
import {
  responsiveScreenFontSize,
  responsiveScreenHeight,
  responsiveScreenWidth,
} from 'react-native-responsive-dimensions';
const EarningStyle = StyleSheet.create({
  header: {
    height: 80,
    width: '100%',
    backgroundColor: '#0C3384',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: responsiveScreenWidth(4),
  },
  backIcon: {
    height: responsiveScreenHeight(6),
    width: responsiveScreenWidth(12),
  },
  headerTitle: {
    fontWeight: '700',
    fontSize: responsiveScreenFontSize(3),
    color: '#FFF',
    marginLeft: responsiveScreenWidth(5),
  },
  switchContainer: {
    width: '90%',
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ccc',
    flexDirection: 'row',
    alignSelf: 'center',
    marginVertical: responsiveScreenHeight(2),
    position: 'relative',
  },
  slider: {
    position: 'absolute',
    width: '33.3%',
    height: '100%',
    backgroundColor: '#0A2C7D',
    borderRadius: 25,
  },
  option: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0A2C7D',
  },
  selectedText: {
    color: '#fff',
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionContainer: {
    backgroundColor: '#f8f9fa',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  amount: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0A2C7D',
    marginBottom: 5,
  },
  details: {
    fontSize: 16,
    color: '#666',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: 'red',
    padding: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 10,
    paddingTop: responsiveScreenHeight(20),
  },
  amount: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0A2C7D',
    marginBottom: 10,
  },
  graphStyle: {
    marginVertical: 8,
    borderRadius: 16,
  },
  TodayTotalRidesEarningValue: {
    fontSize: responsiveScreenFontSize(2),
    color: 'green',
    fontWeight: '500',
    lineHeight: 30,
  },
  TodayTotalRidesEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  TodayTotalEarningsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  TodayTotalEarningsBorder: {
    borderBottomColor: '#000',
    borderBottomWidth: 2,
    paddingTop: responsiveScreenHeight(1),
  },
  TodayWalletEaringValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  TodayWalletEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  TodayWalletEarningRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  TodayDriverEarningValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  TodayDriverEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  TodayDriverEarningRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  TodayRidesValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  TodayRides: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  TodayRidesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  TodayEarningContainer: {
    paddingTop: responsiveScreenHeight(2),
    paddingRight: responsiveScreenWidth(5),
    paddingLeft: responsiveScreenWidth(5),
  },
  WeeklyTotalRidesEarningValue: {
    fontSize: responsiveScreenFontSize(2),
    color: 'green',
    fontWeight: '500',
    lineHeight: 30,
  },
  WeeklyTotalRidesEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  WeeklyTotalEarningsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  WeeklyTotalEarningsBorder: {
    borderBottomColor: '#000',
    borderBottomWidth: 2,
    paddingTop: responsiveScreenHeight(1),
  },
  WeeklyWalletEaringValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  WeeklyWalletEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  WeeklyWalletEarningRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  WeeklyDriverEarningValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  WeeklyDriverEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  WeeklyDriverEarningRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  WeeklyRidesValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  WeeklyRides: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  WeeklyRidesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  WeeklyEarningContainer: {
    justifyContent: 'flex-end',
    //  alignItems:"flex-end",
    paddingRight: responsiveScreenWidth(5),
    paddingLeft: responsiveScreenWidth(5),
    marginTop: responsiveScreenHeight(30),
  },
  ReportTotalRidesEarningValue: {
    fontSize: responsiveScreenFontSize(2),
    color: 'green',
    fontWeight: '500',
    lineHeight: 30,
  },
  ReportTotalRidesEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  ReportTotalEarningsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ReportTotalEarningsBorder: {
    borderBottomColor: '#000',
    borderBottomWidth: 2,
    paddingTop: responsiveScreenHeight(1),
  },
  ReportWalletEaringValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  ReportWalletEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  ReportWalletEarningRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ReportDriverEarningValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  ReportDriverEarning: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  ReportDriverEarningRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ReportRidesValue: {
    fontSize: responsiveScreenFontSize(2),
    color: '#000',
    fontWeight: '500',
    lineHeight: 30,
  },
  ReportRides: {
    fontSize: responsiveScreenFontSize(2.5),
    color: '#000',
    fontWeight: '600',
    lineHeight: 30,
  },
  ReportRidesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ReportEarningContainer: {
    paddingTop: responsiveScreenHeight(2),
    paddingRight: responsiveScreenWidth(5),
    paddingLeft: responsiveScreenWidth(5),
  },
  DateBtn: {
    width: responsiveScreenWidth(35),
    padding: responsiveScreenWidth(4),
    borderWidth: 1,
    borderColor: 'grey',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: responsiveScreenWidth(2),
  },
  DateBtnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: responsiveScreenWidth(10),
    paddingRight: responsiveScreenWidth(10),
  },
  EarningContainer: {flex: 1},
  TripTypeText: {
    fontWeight: '400',
    fontSize: 18,
    lineHeight: 36,
    color: '#000',
  },
  RideBox: {
    borderWidth: 1,
    borderColor: '#000',
    width: responsiveScreenWidth(90),
    padding: responsiveScreenHeight(2),
  },
  RideBoxView: {
    paddingTop: responsiveScreenHeight(4),
    justifyContent: 'center',
    alignItems: 'center',
  },
  GenerateBtn: {
    width: responsiveScreenWidth(50),
    padding: responsiveScreenHeight(2),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0C3384',
    borderRadius: responsiveScreenWidth(3),
  },
  GenerateBtnText: {
    fontWeight: '400',
    fontSize: responsiveScreenFontSize(3),
    lineHeight: 36,
    color: '#fff',
  },
  GenerateBtnView: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: responsiveScreenHeight(2),
  },

});
export default EarningStyle;
